### ISSUE TITLE
CPU usage growing up 25% on each serial port open

### ISSUE THREAD

**Issue by jmb-oliveira** [qzind/qz-print#135]
Hello,

I'm testing qzTray with a Serial Port Printer and having problems with CPU usage growing up by 25% on each Port Open action.

I'm having this issue on many windows 7 64-bits machine and Qz Tray 1.9.5, and i'm testing on live official demo https://demo.qz.io

If I "Open Port", "Send Port Cmd", "Close Port" and "Open Port" again, the CPU usage grows 25%.
The real problem's even when I close the browser tab, CPU usage still high and not reduce.

**Comment by tresf** [comment]
Confirmed using [`com0com`](https://powersdr-iq.googlecode.com/files/setup_com0com_W7_x64_signed.exe) emulator with `QZ Tray 1.9.5` and Windows 10 x64.

In my tests, the "Send Port Cmd" was not needed in order to reproduce the high CPU utilization.

Note, this bug is **NOT** reproducible on the 2.0 branch.

Assigning @Vzor-

**Comment by jmb-oliveira** [comment]
**NOT** reproducible on the 2.0 branch and windows 7 x64 too

**Comment by tresf** [comment]
This fix will be available in 1.9.6.

**Comment by tresf** [comment]
@jmb-oliveira please try our 1.9.6 build here:
https://github.com/qzind/qz-print/releases/tag/v1.9.6

**Comment by jmb-oliveira** [comment]
Very thanks, @tresf 

I'm using the 2.0-dev and working well :)
We'll wait the 2.0 release

**Comment by tresf** [comment]
@jmb-oliveira ok great.  Offtopic of course, but we've released RC1 here: https://github.com/qzind/qz-print/releases/tag/2.0.0-RC1
