### ISSUE TITLE
Remove QZ Tray startup and exit popups

### ISSUE THREAD

**Issue by nhouse** [qzind/qz-print#151]
When QZ Tray is started a popup is shown saying something like "QZ Tray started on ports xxx and xxx." The popup must be manually closed by clicking the OK button. This popup is unnecessary and annoying. If there is an error starting, then by all means show an error, but the popup being shown when startup is successful is pointless.

When closing QZ Tray by clicking on the icon in the system tray -> Exit there is a confirmation popup and "OK" must be pressed. This popup is also unnecessary and annoying.

Please consider removing these popups.

Thanks!

**Comment by tresf** [comment]
Related #92.
The startup message is used to notify of successful startup and which ports are actively being used.  I agree that some of this information this has limited use to a non-developer, however each platform has different ways of showing this Tray Icon, and its "annoyance" factor differs between platforms.

Are you by chance using a Mac?  Mac's notification system didn't exist when Java wrote the notification support, so it is quite annoying on Mac specifically as it never hides. I've written a shim to use the native notifications, but they break on older OSX versions and they open a script editor when clicked, so the code was never committed.

Since Mac displays all Tray icons by default, the visibility of the software is much more noticeable when compared to Windows.  Perhaps we consider hiding notification on Mac only.

Windows will auto-hide the display after a timeout period.

> Exit there is a confirmation popup and "OK" must be pressed

These are two separate, unrelated issues.  Please file a separate bug report.

**Comment by ocaloke** [comment]
If we cannot mimic the same behavior on the Mac (auto-hide the display after a timeout)  then we should hide it on the Mac. Same thing for the exit pop-up.

**Comment by tresf** [comment]
@ordercup,

Thanks for the Mac feedback, although for clarification's sake, I'd like the the O.P. to confirm his platform, which will put his request in better context.  

The exit pop-up is not related to the notification center.  It is a separate request with a separate fix and should be discussed separately.

**Comment by tresf** [comment]
Closed via 1899365.  Exit pop-up too.  Error messages will still be shown.
