### ISSUE TITLE
About free version

### ISSUE THREAD

**Issue by tasarsu** [qzind/qz-print#48]
First of all thank you for this great plugin.

I tried your applet for seamless prints from browser but saw warning messages on every single print job. Is it possible to remove warnings in free version?

**Comment by klabarge** [comment]
Unfortunately it is not possible to remove the warnings in the free version.  For security reasons, all print requests must be digitally signed. If they are not, a warning will appear on each print.  To sign a request, you must obtain an Intermediate Signing Certificate from QZ Industries, LLC, which is included  in the premium version of QZ Print.

**Comment by tasarsu** [comment]
But it is not suitable for production use why do you call it free. It can only be ok for testing issues before buying your commercial product.

**Comment by tresf** [comment]
@tasarsu 

It is not **yet** possible to suppress the warnings in the free version, we may offer this at a later time.  Our priority is to service and support those already subscribed with a version capable of surviving the removal of NPAPI from Chrome which will happen in September.

Free users can still use the legacy Java plugin which still allows the suppression of warning dialogs through manual workarounds.

QZ-Tray will likely have similar workarounds in the future.

For now, if you require a demo, you can contact support and we will be able to offer a time-limited certificate (i.e. 30 days) so that you can try before buy.

**Comment by tresf** [comment]
And the link for reference:
https://github.com/qzind/qz-print/wiki/Legacy-Import-Certificate
