### ISSUE TITLE
Compile Error on windows 8.1

### ISSUE THREAD

**Issue by bkrajendra** [qzind/qz-print#63]
I'm getting compile error in windows 8.1
with latest qz-print v 1.9

```
compile-applet:
    [mkdir] Created dir: D:\xampp\htdocs\pos\qz-print-1.9\qz-print-1.9\out\build
\applet
    [javac] Compiling 58 source files to D:\xampp\htdocs\pos\qz-print-1.9\qz-pri
nt-1.9\out\build\applet
    [javac] D:\xampp\htdocs\pos\qz-print-1.9\qz-print-1.9\src\qz\PrintApplet.jav
a:87: error: cannot find symbol
    [javac]         window = netscape.javascript.JSObject.getWindow(this);
    [javac]                                              ^
    [javac]   symbol:   method getWindow(PrintApplet)
    [javac]   location: class JSObject
    [javac] 1 error

```

**Comment by tresf** [comment]
Hi @bkrajendra.

Some more details are needed to know for sure, but this is a known JavaFX blunder by Oracle introduced with JDK 7.  Here's a good article about it:

http://stackoverflow.com/questions/13953920/not-able-to-resolve-jsobject-in-a-java-applet-project

What we've done is modify the build.xml to accommodate for the jar search order.

This search order is done here [`build.xml#L37`](https://github.com/qzind/qz-print/blob/1.9/build.xml#L37) by putting the Applet's plugin.jar in a higher order when doing classpath searching.

Since you have this issue despite the fix in our build file, I can only imaging you are using something like Eclipse or Netbeans which may override the classpath.  We haven't tried on those systems, but the general instructions should be similar to what we've documented for IntelliJ here: https://github.com/qzind/qz-print/wiki/Compiling#intellij

Specifically, the part "Make sure plugin.jar is at the top of the Dependencies listing".

Please post your details and progress.  If you'd prefer to use this location (GitHub) rather than the mailing list, that is fine too.

**Comment by bkrajendra** [comment]
@tresf thanks for the detailed reply..
But its not helping me.. as Ive tried many things but still getting same error.
I understand the problem plugin.jar. but dont know how to fix it as its already applied.
let me give u details about what I'm doing.

1) Ive cloned latest repo with git.
2) I'm using ant build command line to build the project (Not using any IDE)
3) Ive tried many solution given for similar issues, upgraded JDK, JAVA to latest 1.8
tried to replace plugin.jar in lib folder with plugin.jar from java bin folder.
I'm not good with Java Build system hence not getting what exactly to do to make it working.

4) Finally I tried to Build it with IntelliJ. and waahhh.. It compiled successfully.
but now its not executing as per ant build target. 
I do not know how to execute build target "ant nsis" from IntelliJ..
Or how to get applet or jar from Intellij... as it only show compiled successfully, but do not generate any jar, applet or setup.
Please help me to resolve both of these issue..
Ive successfully run it from intelliJ.

It'll be nice if I can build it from commandline as IntelliJ is very Heavy IDE and its of no use for me.

My System Detail:
OS: Windows 8.1 Pro
Java/JDK 1.8+, All java ENV variables configured

error screenshot is attached!
![qz1](https://cloud.githubusercontent.com/assets/994083/8935084/8d268344-3568-11e5-9d78-e6770cc67eb3.PNG)

**Comment by bkrajendra** [comment]
Sorry accidently closed issue.. now reopened it.

**Comment by klabarge** [comment]
@bkrajendra 

I just verified that our compiling guide works on Windows 8.1.   Have you made sure that you installed all of the dependencies properly?  

I followed the links in [this tutorial](https://github.com/qzind/qz-print/wiki/Install-Dependencies) and installed the latest version of each, taking the defaults (except enabling the Windows command prompt for Git).

I used this convention when setting up my ENV Variables:

Assume Ant is installed in `c:\ant\`. The following sets up the environment:
`set ANT_HOME=c:\ant`
`set JAVA_HOME=c:\jdk1.7.0_51`
`set PATH=%PATH%;%ANT_HOME%\bin`

I then executed the following 4 commands (following [this guide](https://github.com/qzind/qz-print/wiki/Compiling)) and they worked perfectly.
1. Pulled in the latest source code
   `cd qz-print`
   `git pull`
2. Compiled
   `ant`
3. Packaged
   `ant nsis`

It looks like you are having issues packaging the software with `ant nsis`.  You were successful in compiling the software using `ant`?

**Comment by bkrajendra** [comment]
Thanks! I'll try and get back here..

**Comment by bkrajendra** [comment]
atlast .. It compiled ...!
Don't know exactly how. but what I did last time was upgraded jdk to 1.8.0_51
I just saw your post today... rechecked all my ENV path vars... n again executed 
ant and ant nsis ... 
ant compile with success, but 'ant nsis' did throw error:

```
BUILD FAILED
d:\xampp\htdocs\pos\qz-print-1.9\qz-print-1.9\build.xml:301: Execute failed: jav
a.io.IOException: Cannot run program "makensis": CreateProcess error=2, The syst
em cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
```

nsis is installed.

But at least it solved my problem ...
I got applet and jar compiled and also got nsis script.
I compiled nsis script manually and also manage to get installer..
Everything working fine.. except above error..

Thank You all!

**Comment by bkrajendra** [comment]
Finally BUILD SUCCESSFUL :+1: 
Solved makensis issue by adding it to path var. (C:\Program Files (x86)\NSIS)

**Comment by tresf** [comment]
> Solved makensis issue by adding it to path var. (`C:\Program Files (x86)\NSIS`)

Thanks for the update.  I'm confused as this shouldn't be needed (and isn't on any of my systems). Here's the line that tries the x86 directory:

https://github.com/qzind/qz-print/blob/1.9/build.xml#L321

``` xml
    <!-- Win32 makensis -->
    <target name="nsisbin-2" depends="init" unless="env.ProgramFiles(x86)">
        <property name="nsisexe" value="${env.ProgramFiles}/NSIS/makensis.exe"/>
    </target>

    <!-- Win64 makensis -->
    <target name="nsisbin-3" depends="init" if="env.ProgramFiles(x86)">
        <property name="nsisbin" value="${env.ProgramFiles(x86)}/NSIS/makensis.exe"/>
        <!--           HERE --------------------------------^                      -->
    </target>
```

**Comment by tresf** [comment]
At a closer look, you may be failing this check:

``` xml
    <target name="nsisbin-1" depends="init" unless="env.windir">
        <property name="nsisbin" value="makensis"/>
    </target>
```

In this case, `makensis` is called directly (assumes it is on the path), but this is dependent on an ENV variable "windir", referred to by this code:   `<property environment="env"/>` and then the task *should* be skipped via `unless="env.windir">`

This is how Linux works (all binaries are already on the path) but Windows shouldn't ever get int this block because of the WINDIR environmental variable.
