### ISSUE TITLE
Fix "Intranet" Zone in IE

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#67]
This bug has been migrated to https://github.com/qzind/tray/issues/6.

---

Currently, we use a brute-force method in IE to allow WebSocket communication by telling the computer to stop `Automatically detect intranet network`

![image](https://cloud.githubusercontent.com/assets/6345473/9043559/5c28cd30-39e4-11e5-9121-eeb1e19adc47.png)

This is a stop-gap which has adverse side-effects on a corporate LAN as it prompts for login credentials when accessing web resources.

**Comment by tresf** [comment]
@klabarge can you run with this one?  @Vzor- or myself can commit the code changes, we just need to know which setting(s) to change.

**Comment by klabarge** [comment]
@tresf yes, I will see if I can come up with an alternative solution.

**Comment by tresf** [comment]
@klabarge is there anything that we can do with this?  Last we spoke is sounded like you were unable to reproduce the issue, which leads me to believe we should close this out as `wontfix` now and reopen if and when we can reliably reproduce.

**Comment by klabarge** [comment]
@tresf As discussed, I will install QZ Tray on a fresh computer that is on a domain. I will save the registry settings before and after in case we can reproduce the problem.  I will report back here with my findings.

**Comment by klabarge** [comment]
I was able to successfully/reliably reproduce this problem.

Steps:
1. On a clean PC, tested that I could access network resources without being prompted for credentials
2. Installed QZ Tray
3. Accessed a network resource and was prompted for credentials
4. Uninstalled QZ Tray
5. Accessed a network resource and I was _still_ prompted for credentials
   - The setting changed on installation is not reverted, and I had to manually check "automatically detect intranet network" in order to for network resources to work normally

This is a bit puzzling as this issue seemed to automatically resolve itself for both of us.  

I entered my password in and selected "Remember my credentials".  Upon resetting these settings, I was still prompted to login before being allowed to access network resources.

**Comment by tresf** [comment]
@klabarge some more details on this... 

I couldn't understand why this was so unpredictable... this is why:

:white_check_mark: Run from local hard drive, WebSocket Succeeds
:no_entry: Run from https://demo.qz.io, WebSocket is blocked unless the above settings are checked

Hopefully that puts more context into this issue.

**Comment by tresf** [comment]
This bug has been migrated to https://github.com/qzind/tray/issues/6.
