### ISSUE TITLE
Cannot generate certificate/keys in Safari

### ISSUE THREAD

**Issue by klabarge** [qzind/qz-print#69]
I tested on both of the below versions with the same results.

```
Version 5.1.7 (7534.57.7)
Version 8.0.7 (10600.7.12)
```

When trying to generate both the CSR and the key pair, the browser hangs at "Generating key pair"  and never completes.

Inspect element shows the error: 

```
TypeError: 'undefined' is not an object (evaluating 'window.crypto.subtle.generateKey')
```

![image](https://cloud.githubusercontent.com/assets/12505463/9119044/9a278fda-3c42-11e5-84e4-7176889fcdde.png)

**Comment by tresf** [comment]
Related:  http://stackoverflow.com/questions/31798241/safari-webcrypto-api-rsa-oaep-encryption

Per https://www.theseus.fi/bitstream/handle/10024/92960/Web_Cryptography_API_Luoma-aho.pdf?sequence=1, Apple's API hasn't matured yet, so they're using a different namespace.  This should fix it:

``` javascript
// fix safari crypto namespace
if (window.crypto && !window.crypto.subtle && window.crypto.webkitSubtle) {
    window.crypto.subtle = window.crypto.webkitSubtle;
}
```

**Comment by tresf** [comment]
FYI, Kyle, wrong repository, this should be on qz.io. :+1:

**Comment by tresf** [comment]
@klabarge can you re-test now that we've applied https://github.com/qzind/qz.io/commit/daf14d6c8dc53b1fef34fa8987c4eb5d122cffeb

**Comment by klabarge** [comment]
Same error is displayed after the change:
![image](https://cloud.githubusercontent.com/assets/12505463/9121474/888229bc-3c50-11e5-987e-c56a65538139.png)

**Comment by tresf** [comment]
AFAIk, crypto is only supported on Safari 8.  Which Safari version are you testing against?

**Comment by klabarge** [comment]
Both versions 5 and 8 still hang on "Generating key pair..."

**Comment by tresf** [comment]
Right, but the error on 8 is no longer `TypeError: 'undefined' is not an object (evaluating 'window.crypto.subtle.generateKey')`, so that portion is fixed now.  I'll have to put some more time into this.  It appears it's at least getting further now.

**Comment by tresf** [comment]
Since there are no errors I have the feeling there's some callback or promise not getting returned from JavaScript.

@Lukas-W opinions welcome.

**Comment by tresf** [comment]
I'm pretty sure this is due to the download never happening, which is sad... Ultimately, downloading a JavaScript generated "Blob" file is unsupported in Safari.  We'd have to farm this off to the server currently, which defeats the purpose of a private key. 

https://bugs.webkit.org/show_bug.cgi?id=102914#c25

**Edit:** Probably a short-term solution (while we all wait for Apple to fix this functionality) is to display a warning for Safari being unsupported, or set a timeout value that displays a generic "please try another browser or clear your cache" warning.

@Lukas-W although this is in the wrong repo, I'll still wait for you to chime in before closing this out.

-Tres

**Comment by tresf** [comment]
@Lukas-W shall we just put a warning for Safari users?  It seems Safari doesn't have the blob support which would be required for downloading the client-side private key.

**Comment by tresf** [comment]
Moved to https://github.com/qzind/qz.io/issues/32
