### ISSUE TITLE
How to suppress Action Required prompt?

### ISSUE THREAD

**Issue by bkrajendra** [qzind/qz-print#72]
I tried instructions at https://qz.io/wiki/signing-messages also tried with self signed cirtificate and qz-print certificate..
But no success.
I know its explained at many places here, but i could not follow it.
Is it possible to suppress this prompt for open source version with self signed certificate?
This what Ive done:
Edited sample.html as..

```
function signRequest(toSign, callback) {
    $.ajax({
        method: 'GET',
        url: 'http://localhost/pos/qz-clean/new/qz-print/assets/signing/sign-message.php?request=' + toSign,
        async: false,
        success: callback // Data returned from ajax call should be the signature
    });
    /*callback();*/
}
```

content of sign-message.php file

```
$KEY = 'private-key.pem'; //this file is there in same folder as sign-message.php 
$PASS = 'S3cur3P@ssw0rd';
header('Access-Control-Allow-Origin: *');
$req = $_GET['request'];
$privateKey = openssl_get_privatekey(file_get_contents($KEY), $PASS);
```

private-key.pem this same file that comes with source.
also tried with my own private key generated with keytools.

(I'm Sorry if I'm asking already answered question.)

![qz2](https://cloud.githubusercontent.com/assets/994083/9131652/3a71a5f2-3d0b-11e5-8170-a2eed4988f9f.PNG)

**Comment by tresf** [comment]
No this is not possible currently with QZ Tray unless you have purchased a
license.

We do have instructions for suppressing warnings with the free version of
QZ Print (Legacy Java Applet), but we have not yet added silent printing
for QZ Tray without a premium subscription.

**Comment by bkrajendra** [comment]
Thanks

**Comment by hendranata** [comment]
but now we can do self signed right?

**Comment by tresf** [comment]
> but now we can do self signed right?

Correct.  Self-signed certificates are now supported in the codebase in 2.0.1 via command line switch and will be available at compile-time and via configuration file starting with 2.0.2.

**Comment by hendranata** [comment]
It looks awesome but do we need to do compiling? Or just use existing qz-print.jar and change the self sign certificate

**Comment by riaanvdl** [comment]
Its laid out pretty well step by step on this page hope it helps:

*@tresf Link removed, email sent to author.*

**Comment by hendranata** [comment]
Hehe we have done that last year.
Yes indeed we can recompile the qz tray apps using own self sign certificate :)
We can save big money

**Comment by tresf** [comment]
> We can save big money

I feel the need to chime in here... Please have some common courtesy.  Although we don't discourage making the software "popup free", we also can't survive without the revenue.  We have bills to pay too.  

Furthermore, we have several clients that cannot afford our price point but we do our best to make the subscription model work.

Although QZ Tray is open source, QZ Tray is also largely (99%) supported by [QZ Industries, LLC](https://qz.io).  Don't believe us?  Look at the project [commit history](https://github.com/qzind/tray/commits).  With the exception of a few community contributors (mostly just `@dsanders11`), the research, development and support is all paid for by QZ Industries, LLC.

QZ Industries, LLC owns the copyright to the codebase and we also own and manage our pages here on GitHub, so we are responsible for its content.  The project is predominantly used by businesses (not individuals) so it has never been able to survive as purely community-supported.  Because of this problem... my brother @lite1979 and I decided in 2013 to turn the codebase into a real company.  It simply cannot survive without a steady revenue stream.

We normally don't discuss business here, but this time I feel we have to.  We're FOSS users and FOSS promoters and we do believe -- fundamentally -- in open source.  We also respect the FOSS community and don't use our bug tracker or mailing list to upsell our product.  We ask that you don't down-sell it either!

To put this into an analogy...  "It's fine you want to give away free lemonade, but don't do it at our stand." ❤️ 

If you want QZ Tray to be around for years to come, it's paramount that the community is encouraging to the business model.  Without it, the software wouldn't exit.
