### ISSUE TITLE
qz.appendImage() Hard crash on Mac

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#75]
The attached image crashes QZ Tray out completely with a Mac stacktrace when printed using qz.appendImage().

![image_sample_orig_broken](https://cloud.githubusercontent.com/assets/6345473/9427295/2ca0aee8-4943-11e5-9b16-845eb7e7ad96.png)

> \* Image used with written permission from bug submitter.

**Comment by tresf** [comment]
The bugs seems to be specific to Java, Mac and the image format, which is a `1-bit` Grayscale PNG image.

A work-around is to use ImageMagic to perform image conversion and forcing the PNG color-type property to zero, which bumps the `1-bit` to `8-bit` and prevents the crash from occurring via `-define png:color-type=0`.  This has the benefit of maintaining the grayscale palette, but a downside of doubling the image size (e.g. 13KB to 26KB)

``` bash
convert original-1-bit.png -define png:color-type=0 fixed-8-bit.png
```

**Comment by Vzor-** [comment]
This issue was with OS X 10.10 but not 10.9.5. It only happens with images that had a palette smaller than 16 colors, or a 4 bit pixel data size.

The fix was to take the palette out and putting it in a 256 color buffered image we can pad out the palette to 8 bits without introducing dithering. **Note:** If any dithering DOES happen it is due to the strangeness of Java and not the palette. 

After the fix we had a similar issue with a full ARBG image that had a `BufferedImage.getType()` of `TYPE_CUSTOM`, crash. If any more images crash, log their type, look up the enum in the constant-values section of JavaDocs, then add it to the `badTypes` array.
